From golang:1.22-alpine AS builder
WORKDIR /the/workdir/path
COPY . .
RUN go mod download
RUN go build -o product_catalog ./

FROM apline AS release 
WORKDIR  /the/workdir/path
COPY ./products ./products
COPY --from=builder /the/workdir/path/product-.catalog ./

ENV PRODUCT_CATALOG_PATH = 8088
ENTRYPOINT [ "./product_catalog" ]